---
version: 2.1
executors:
  docker:
    docker:
      - image: docker:git
    environment:
      DOCKER_IMAGE_NAME: nephosolutions/packer
jobs:
  build:
    executor:
      name: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t "${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}" .
      - run:
          name: Push Docker image
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            docker push "${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}"
      - when:
          condition:
            not:
              equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                name: Tag and push branch
                command: |
                  docker tag  "${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKER_IMAGE_NAME}:${CIRCLE_BRANCH##*/}"
                  docker push "${DOCKER_IMAGE_NAME}:${CIRCLE_BRANCH##*/}"
      - when:
          condition:
            and:
              - equal: [ "master", << pipeline.git.branch >> ]
              - not: << pipeline.git.tag >>
          steps:
            - run:
                name: Tag and push latest
                command: |
                  docker tag  "${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKER_IMAGE_NAME}:latest"
                  docker push "${DOCKER_IMAGE_NAME}:latest"
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Tag and push release
                command: |
                  docker tag  "${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}" \
                    "${DOCKER_IMAGE_NAME}:${CIRCLE_TAG##v}"
                  docker push "${DOCKER_IMAGE_NAME}:${CIRCLE_TAG##v}"
workflows:
  version: 2
  integration:
    jobs:
      - build:
          context: docker-hub
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+){2}(-.*)?$/
